display-name: 'Default'

difficulties:
  basic:
    contents:
      '0':
        material: STONE

  normal:
    contents:
      '0':
        material: IRON_BLOCK

  insane:
    contents:
      '0':
        material: DIAMOND_BLOCK