display-name: 'Default'

difficulties:
  basic:
    contents:
      '100':
        material: STONE

  normal:
    contents:
      '100':
        - material: ENDER_PEARL
          amount: 1
        - material: END_STONE
          amount: 14

  insane:
    contents:
      '100':
        material: DIAMOND_BLOCK