server:
  # Whether this server should use proxy mode.
  # When you enable proxy mode, make sure you select the right server type and enter the correct name as described.
  proxy: false
  # When using Skywars in proxy mode, SWR needs to know what type of server this is in order
  # to run certain processes. Options are: LOBBY and GAME.
  # Please note that local games can NOT run on lobby servers.
  type: "GAME"
  # If using a proxy like bungeecord or velocity, set the server name of this server (case-sensitive).
  # If this value is incorrect, skywars won't be able to send players to the games.
  name: "default"

storage:
  # The type of storage to use for player data.
  # Could be: SQLite, MySQL, MongoDB*, Redis*
  # * extension required
  type: MySQL
  hostname: localhost
  port: 3306
  username: user
  password: pass
  database: skywarsreloaded
  use-ssl: true

# The number of instances of a map template that will be loaded when the server starts.
game-instances:
  # Instance options for when the plugin is running on only one server
  local-mode:
    idle-instances: 3

  # Instance options for when the plugin is running on a multi-server network (bungeecord / velocity)
  proxy-mode:
    # Dynamic mode features only work with the SkywarsReloaded Extension
    dynamic-mode:
      # Minimum amount of worlds loaded and ready to accept maps upon request
      min-idle: 3
      # Maximum amount of games that can run on this server
      max-instances: 10
    # Amount of fixed instances for each map/template on this server
    # Set fixed-templates: {} to have 0 fixed template instances
    # (you probably want dynamic mode if you are doing this)
    # Note: Without the SkywarsReloaded Extension, the maximum instances on each game server is 3
    fixed-templates:
      default: 1
      # map_name_a: 2
      # map_name_b: 1

world-loader:
  # Whether to automatically use slime worlds if SlimeWorldManager (SWM) is detected.
  enable-swm: true

menus:
  join:
    # Options: NAME, NAME-REVERSED, TEAMSIZE, TEAMSIZE-REVERSED, WAITING, WAITING-REVERSED
    sort-by: TEAMSIZE
  kits:
    # Options:
    # - OUTLINED (leaves the border slots empty)
    # - FILLED (fills every possible slot)
    layout: OUTLINED
    # Whether to automatically place kits in the menu based on their load orders.
    # Enabling this will override custom menu positions, so be careful!
    auto-layout: false

items:
  general:
    close:
      material: BOOK
    confirm:
      material: LIME_DYE
    deny:
      material: RED_DYE
  kits:
    deselect:
      material: BARRIER

game:
  # Timer values are in seconds
  timers:
    waiting-lobby: 180
    waiting-lobby-full: 10
    waiting-cages: 30
    waiting-cages-full: 15
    ending: 20
  cages:
    separate-cages: false
  chests:
    max-items: 26
    max-items-double: 53
  solo-waiting-lobby: false

parties:
  # If this is set to false, you won't be permitted to join a game that can't fit the entire party into one team.
  allow-dispersed-parties: true