storage:
  type: MySQL
  hostname: localhost
  username: user
  password: pass
  database: skywarsreloaded
  use-ssl: true

world-loader:
  # awtoamticaly use slime worlds if SlimeWorldManager (SWM) was detected.
  enable-swm: true