name: SkyWarsReloaded
main: net.gcnt.skywarsreloaded.bukkit.BukkitSkyWarsReloadedPlugin
version: 6.0.0
api-version: 1.13
author: GaagjesCraft Network Team (GCNT)
description: Bukkit's best Skywars plugin.
depend:
  - WorldEdit
softdepend:
  - FastAsyncWorldEdit

commands:
  skywars:
    description: Main command.
    aliases: [skywarsreloaded, sw, swr]
  skywarsmap:
    description: Map management command.
    aliases: [swmap, swm]