display-name: Boom
icon: TNT
unavailable-icon: BARRIER
description: TNT says Boom!
slot: 1
lore:
  - ''
  - ''
  - ''
requirements:
  permission: false # needs permission
  cost: 1000 # or needs to pay 1k cash
  stats: # or needs at least the following stats
    kills: 100
    wins: 100

contents:
  armor:
    helmet: ''
    chestplate: ''
    leggings: ''
    boots:
      material: DIAMOND_BOOTS
      enchantments:
        - PROTECTION_ENVIRONMENTAL:1
  inventory:
    '1':
      material: TNT
      amount: 6
    '2':
      material: DARK_OAK_PRESSURE_PLATE
      amount: 2
    '3':
      material: LEVER
    '4':
      material: REDSTONE
      amount: 4

effects: # list of option effects to be applied to the player during the game.
  # format: <TYPE>:[duration]:[amount]
  - STRENGTH:1