display-name: Boom
icon:
  material: TNT
unavailable-icon:
  material: TNT
description: TNT says Boom!
lore:
  - '&8- &7Diamond Boots &8(&aProtection I&8)'
  - '&8- &7TNT &b(6x)'
  - '&8- &7Lever'
  - '&8- &7Redstone &b(4x)'
requirements:
  permission: false # needs permission
  cost: -1 # or needs to pay 1k cash -- set to -1 to make non-buyable with coins.
  stats: # or needs at least the following stats
    kills: 100
    wins: 100

contents:
  armor:
    helmet: ''
    chestplate: ''
    leggings: ''
    boots:
      material: DIAMOND_BOOTS
      enchantments:
        - "protection:1"
  inventory:
    '1':
      material: TNT
      amount: 6
    '2':
      material: DARK_OAK_PRESSURE_PLATE
      amount: 2
    '3':
      material: LEVER
    '4':
      material: REDSTONE
      amount: 4

effects: # list of option effects to be applied to the player during the game.
  # format: <TYPE>:[duration]:[amount]
  - "strength:1"